import { ProjectWorkItem } from "../types";

export const mockProjectItems: ProjectWorkItem[] = [
  {
    id: "REQ-1024",
    title: "会员中心改版交互与视觉设计",
    project: "会员增长",
    url: "https://example.feishu.cn/project/REQ-1024",
    creator: "产品-林乔",
    assignee: "周然",
    priority: "P0",
    status: "设计中",
    estimateHours: 14,
    dueDate: "2026-08-18",
    createdAt: "2026-08-11T09:30:00Z",
    labels: ["设计", "会员"],
    type: "UX"
  },
  {
    id: "REQ-1031",
    title: "订单详情页空状态补齐",
    project: "交易体验",
    url: "https://example.feishu.cn/project/REQ-1031",
    creator: "产品-陈嘉",
    assignee: "李安",
    priority: "P2",
    status: "待设计",
    estimateHours: 5,
    dueDate: "2026-08-20",
    createdAt: "2026-08-12T03:20:00Z",
    labels: ["UI"],
    type: "视觉"
  },
  {
    id: "REQ-1033",
    title: "增长活动落地页视觉方案",
    project: "暑期增长活动",
    url: "https://example.feishu.cn/project/REQ-1033",
    creator: "产品-王一",
    assignee: "周然",
    priority: "P1",
    status: "待评审",
    estimateHours: 8,
    dueDate: "2026-08-16",
    createdAt: "2026-08-12T06:40:00Z",
    labels: ["视觉", "活动"],
    type: "视觉设计",
    sequence: 1
  },
  {
    id: "REQ-1037",
    title: "支付失败链路提示优化",
    project: "支付稳定性",
    url: "https://example.feishu.cn/project/REQ-1037",
    creator: "产品-赵晴",
    assignee: "韩予",
    priority: "P1",
    status: "阻塞",
    estimateHours: 10,
    dueDate: "2026-08-21",
    createdAt: "2026-08-12T08:10:00Z",
    labels: ["交互", "风险"],
    type: "UX",
    designOwner: "韩予",
    sequence: 2
  },
  {
    id: "REQ-1040",
    title: "帮助中心搜索体验优化",
    project: "客服效率",
    url: "https://example.feishu.cn/project/REQ-1040",
    creator: "产品-林乔",
    priority: "P2",
    status: "待设计",
    estimateHours: 6,
    dueDate: "2026-08-23",
    createdAt: "2026-08-12T09:50:00Z",
    labels: ["体验设计"],
    type: "UX",
    sequence: 4
  },
  {
    id: "REQ-1046",
    title: "线上投诉入口临时改版",
    project: "线上风险处理",
    url: "https://example.feishu.cn/project/REQ-1046",
    creator: "项目-沈宁",
    assignee: "周然",
    priority: "P0",
    status: "待设计",
    estimateHours: 12,
    dueDate: "2026-08-17",
    createdAt: "2026-08-13T02:10:00Z",
    labels: ["UI", "插单", "线上问题"],
    type: "视觉设计",
    sequence: 0,
    isRush: true,
    rushReason: "线上投诉量上升，需要优先处理入口说明与页面路径"
  },
  {
    id: "REQ-1042",
    title: "服务端日志采样策略调整",
    url: "https://example.feishu.cn/project/REQ-1042",
    creator: "产品-后端",
    assignee: "工程-齐明",
    priority: "P2",
    status: "待开发",
    estimateHours: 6,
    createdAt: "2026-08-12T10:00:00Z",
    labels: ["后端"],
    type: "研发"
  }
];
